### ISSUE TITLE
SSH connection to the bastion can fail if the operator's agent tries too many other keys first

### ISSUE THREAD

**Issue by dale-c-anderson** [aws-samples/aws-amazon-eks-ansible-example#3]
**Original problem**
The task `Get AWS Account Information` in the deploy playbook fails to connect to the bastion, with the SSH error `Too many authentication failures`.

**Root cause**
I have 7 ssh keys loaded in my agent:
```
$ ssh-add -l|wc -l
7
```
Evidently too many of these were tried before the playbook's own generated key was tried. Retrying the playbook without any adjustments to SSH configuration results in the same error. Attempting to SSH manually to the bastion also results in the same error.

**My Fix**
Appdending `-o IdentitiesOnly=yes` to the `ssh_args` in the playbook's `ansible.cfg` file ensures the playbook only tries the single key that was generated, thus allowing the playbook to connect to the bastion and continue executing.

**Comment by couchgott** [comment]
ty. i'll add this to the cfg with the next release :=)
