### ISSUE TITLE
eks-container-insights.task.yaml still has an example name hardwired in it

### ISSUE THREAD

**Issue by dale-c-anderson** [aws-samples/aws-amazon-eks-ansible-example#4]
**The Problem**

When `eksexample_clustername` in `/vars/static/defaults.yaml` is changed from its default, the `create Roles and Policies for container insights` task always fails to create it's cloudformation stack. 

**Root Cause**

The default value of the stack name is wired into the shell command in the  `get notegroups rolename` task. 

So instead of describing the stack that was created, the command tries to describe a stack that doesn't exist, causing the next task to fail.

**The fix**

Replace the static portion of the stack name being queried with the portion that's expected from the variables file:

```diff
-  shell: > 
-    aws cloudformation describe-stack-resources --region {{ eksexample_region }} --stack-name eksctl-{{ eksexample_clustername }}-nodegroup-ansible-eks-testcluster-linux-nodes \
+  shell: >
+    aws cloudformation describe-stack-resources --region {{ eksexample_region }} --stack-name eksctl-{{ eksexample_clustername }}-nodegroup-{{ eksexample_clustername }}-linux-nodes \
```

**Comment by couchgott** [comment]
Hey. That makes sence, seems i've overseen that one .) will be in the next release.
