### ISSUE TITLE
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The config profile (ansible) could not be found"}

### ISSUE THREAD

**Issue by bxc2739** [aws-samples/aws-amazon-eks-ansible-example#9]
TASK [Create EC2 KeyPair] ******************************************************
Monday 02 May 2022  15:40:26 +0000 (0:00:00.023)       0:00:00.325 ************ 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The config profile (ansible) could not be found"}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by couchgott** [comment]
Hey @bxc2739, 

did you ensure the profile "ansible" has been setup at your local CLI setup? 

see: 
"changed": false, "msg": "The config profile (ansible) could not be found"

best,

David

**Comment by bxc2739** [comment]
Hi thanks! I'm trying to run this as playbook yaml inside of web gui console of Ansible Tower/AWX instance, so I need to ssh into that server instance and run aws configure etc to set the right configs beforehand or that can be done inside the gui/web interface itself?

**Comment by bxc2739** [comment]
![image](https://user-images.githubusercontent.com/101810221/166476129-88192809-6c72-4414-97b0-b8c177ba2fd2.png)

**Comment by bxc2739** [comment]
So as a test I unchecked the box called ENABLE PRIVILEGE ESCALATION in Ansible Tower, reran it and getting::

The full traceback is:
  File "/tmp/ansible_ec2_key_payload_sswfsolj/ansible_ec2_key_payload.zip/ansible/module_utils/ec2.py", line 117, in boto3_conn
    return _boto3_conn(conn_type=conn_type, resource=resource, region=region, endpoint=endpoint, **params)
  File "/tmp/ansible_ec2_key_payload_sswfsolj/ansible_ec2_key_payload.zip/ansible/module_utils/ec2.py", line 145, in _boto3_conn
    profile_name=profile,
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/session.py", line 680, in get_component
    return self._components.get_component(name)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/session.py", line 903, in get_component
    self._components[name] = factory()
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/session.py", line 150, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/session.py", line 234, in get_config_variable
    logical_name)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/configprovider.py", line 227, in get_config_variable
    return provider.provide()
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/configprovider.py", line 324, in provide
    value = provider.provide()
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/configprovider.py", line 383, in provide
    config = self._session.get_scoped_config()
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/session.py", line 335, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "force": true,
            "key_material": null,
            "name": "ansible-eks-testcluster-keypair",
            "profile": "ansible",
            "region": "us-west-2",
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "wait": false,
            "wait_timeout": 300
        }
    },
    "msg": "The config profile (ansible) could not be found"
}

**Comment by couchgott** [comment]
hmm, yep i think for a tower runned version you might want to alter the code not to utilize the aws profile (educated guess, delete --profile from all commands, tasks)
then follow: https://docs.ansible.com/ansible-tower/latest/html/userguide/credentials.html to setup your AWS credentials within Ansible tower. 

"should work" w/o a bastian host or sth. 

simplest path: fork this repo, do your changes ;)

**Comment by bxc2739** [comment]
So I don't think that would have worked earlier since I'm now just trying to get it directly run from CLI without the tower GUI and still getting....

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (botocore or boto3) on ip-.us-west-2.compute.internal's Python /usr/libexec/platform-python. 

Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
"

===
ansible 2.9.7
  config file = /tmp/aws-amazon-eks-ansible-example-main/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

**Comment by couchgott** [comment]
thats a different issue. simply your ansible/python environment is not properly setup. e.g. afair (plz ref the readme.md) boto3 needs to be installed on the machine running the playbooks

**Comment by bxc2739** [comment]
Okay I used a local ubuntu vm and was able to run a sample (different script) to get going and created a EC2 instance with playbook so I know that it can at least talk to AWS correctly with ansible, however when running the eks-ansible example am getting 

fatal: [local]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname local: Name or service not known", "unreachable": true}

it wouldn't be having anything to do with the localhost line I had to put at the bottom of /etc/ansible/hosts? I'm able to use playbook to create ec2 instances just fine on the exact setup etc 

[localhost]
local

**Comment by couchgott** [comment]
hostname local: Name or service not known", "unreachable": true}

local is not a valid hostname. 
try localhost. 

Best

**Comment by bxc2739** [comment]
EKSBastionInstancePublicIP
Now getting err :: fatal: [localhost]: FAILED! => {
    "msg": "'EKSBastionInstancePublicIP' is undefined"

This is in reference to the mentioning of ""_For the DNS Automation to work you'll need to have a [Hosted Zone](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/AboutHZWorkingWith.html) setup at your AWS Account_"" ?

**Comment by couchgott** [comment]
Hey, 

you need to ensure the bastion host is build 

(see main Playbook: 

- name: setup bastion host
      include_tasks: ./tasks/bastion.task.yaml
)

if this task has been removed, ensure the resuting variables/parameters are not still used in any of the playbooks. 
otherwise it will try to utilize the parameter as input 
e.g. to connect to the bastion host to execute automation
for instance this variable/paramter is used when deplyoing the k8s cluster and its workload. 

Best

**Comment by andrewpsp** [comment]
A quick summary of the issue from my understanding, it would appear that because the bastion host was not properly built, the creation of the ec2 Keypair was not able to complete successfully causing this failure,.

**Comment by couchgott** [comment]
hmm not sure the original cause but as the user did never reply again i assume it's resolved ;)
